### ISSUE TITLE
Feature to let users specify links to Navbar

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/urchin#70]
Think about how we could let users specify arbitrary links to for the navbar.

As a first pass, this could be a simple toml config feature somehow

```toml
[[navbar.link]]
name = "Google"
url = "https://google.com"
title = "some help text"
```
